# Generated by Django 3.0.6 on 2020-07-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.TextField(default='google.com'),
            preserve_default=False,
        ),
    ]
